### ISSUE TITLE
Unable to sync c1-mainnet

### ISSUE THREAD

**Issue by ircrp** [dcSpark/milkomeda-evm-passive#8]
Since today I am no longer able to sync c1-mainnet, I suspect the static nodes are no longer reachable. This happened to me several days ago and I noticed you guys have updated the static-nodes which fixed it until today.

```
besu_1  | {"timestamp":"2022-04-07T19:19:44,558","container":"docker-desktop","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
besu_1  | {"timestamp":"2022-04-07T19:19:49,559","container":"docker-desktop","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
besu_1  | {"timestamp":"2022-04-07T19:19:54,560","container":"docker-desktop","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
besu_1  | {"timestamp":"2022-04-07T19:19:59,568","container":"docker-desktop","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 0","throwable":""}
```

Checked c1-devnet and it syncs all fine.
Followed troubleshooting and the sync issue persists.

**Comment by ircrp** [comment]
Started debugging the issue and what I've noticed is that I am getting disconnected by the peers with the following reason ```message":"Disconnect - Inbound - 0x04 TOO_MANY_PEERS```

I suspect that there is a limit on the peers I am trying to connect to in terms of how many connections they can handle ? Could you please confirm if that's the case and if there is any plan to increase the capacity and/or open additional static nodes ?

**Comment by charliedimaggio** [comment]
> Started debugging the issue and what I've noticed is that I am getting disconnected by the peers with the following reason `message":"Disconnect - Inbound - 0x04 TOO_MANY_PEERS`
> 
> I suspect that there is a limit on the peers I am trying to connect to in terms of how many connections they can handle. Could you please confirm if that's the case and if there is any plan to increase the capacity ?

I am experiencing the same behaviour.

It doesn't look like there are any easy fixes as it seems, maybe by design, that p2p nodes in the swarm configured using the instructions in this repo are not discoverable and their enode IP is set to 127.0.0.1 due to `nat-method="NONE"` that is set in config.toml [ref: nat-method](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#:~:text=default%20is%20127.0.0.1.-,Info,-If%20%2D%2Dnat%2Dmethod)

**Comment by noirzz** [comment]
have the same issue when trying to sync new node
but the running one have no problem

**Comment by ircrp** [comment]
As per the chat in discord I was told the static nodes have increased the capacity. While it did allowed me to sync up it only latest for about 40 minutes and then all the static nodes have exhausted capacity and I am back out of sync. It seems that the demand is too high for static nodes to handle it going forward. Would it be possible to re-configure the network such that non-static nodes can discover each other ?

**Comment by daichuanliang** [comment]
Hi,  My server is in Japan, I found that I can't connect to the static node.  How should I connect more  peers?

**Comment by kapisolec** [comment]
The same issue happens if I try to use fast sync:
```
{"timestamp":"2022-04-10T13:09:28,955","container":"Ubuntu-2004-focal-64-minimal","level":"INFO","thread":"EthScheduler-Timer-0","class":"WaitForPeersTask","message":"Waiting for 1 total peers to connect. 0 peers currently connected.","throwable":""}
```

**Comment by michaellll** [comment]
I have the same issue and know others also experiencing the same problem
I've tried different combinations of FAST/FULL .. 
and different peers fast-sync-min-peers=1/2/5
stopping and restarting the both the mainnet 
also passive restart of Docker 
nothing's working

**Comment by janbo24** [comment]
Hello, same thing is happening to me, devnet is working without interruptions while mainnet is dropping the sync. Same thing happened around 10 days ago when you resolved the issue. 

When can we expect issue to be resolved and are there any steps that we can do to overcome it until its resolved?

Are there any nodes that we can add

**Comment by SebastienGllmt** [comment]
Hey folks, we're aware of the issue but have been heads-down the past couple of days to get stablecoins and other ERC20 assets onto Cardano (https://twitter.com/Milkomeda_com/status/1513869445764157446)

Fixing this issue will be our next priority. Thank you for your patience 🙏

**Comment by michaellll** [comment]
I just want to say that Milkomeda has great potential but you should have gone directly with Metamask ... I can see people very quickly have become fed up ... also why is it easy to send from Flint to Metamask but you have to go through 2 different bridges to swap back to ADA ... this is retarded seriously ... and I see the drop in interest in this chain because you decided to go with that Flint MM easy ... MM to Flint not

**Comment by RamoDataScience** [comment]
@michaellll can you explain how you solve it please!

**Comment by michaellll** [comment]
> @michaellll can you explain how you solve it please!
so supposedly the devs are drip feeding us "static nodes" ... that's all I can say

**Comment by michaellll** [comment]
you should have left my comment about Flint to Metamask ok 
Metamask to Flint not ok

**Comment by rinor** [comment]
@ircrp @charliedimaggio @noirzz @daichuanliang @kapisolec @janbo24 are you able to connect now?

As @charliedimaggio mentioned https://github.com/dcSpark/milkomeda-evm-passive/issues/8#issuecomment-1092747023 once the static peers reach their limits, we need other community p2p nodes properly configured to accept connections and participate in the p2p network.
We put some links on the README for those interested to configure and participate on p2p discovery, putting them also here:
- https://besu.hyperledger.org/en/stable/HowTo/Find-and-Connect/Bootnodes/
- https://besu.hyperledger.org/en/stable/HowTo/Find-and-Connect/Configuring-Ports/
- https://besu.hyperledger.org/en/stable/HowTo/Find-and-Connect/Specifying-NAT/

**Comment by michaellll** [comment]
will there be a tagging option on the milkomeda chain ... 
ex: being about to tag a creator, like we can on Snowtrace ?
this would be really helpful to tag a creator that creates nothing but rugpulls or honeypots ... 
thx
